spring:
  datasource:
    url: jdbc:h2:mem:decola
    username: luiz
    password:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      setting:
        trace: false
        web_allow_others: false